### ISSUE TITLE
einweggerat can't be compiled due to missing dependencies

### ISSUE THREAD

**Issue by DerekTurtleRoe** [mudlord/misc_stuff#1]
I know you said support would be ignored, but I don't think it was meant to be uploaded unable to be compiled 😅 

The "3rdparty-deps" folder mentioned in multiple places isn't in the repository, so einweggerat can't be compiled. I saw some mentions of libretro.h, but if I create the directories and put the libretro.h in the correct folder it still doesn't compile.

So my questions would be:

1. Was this just mistakenly not commited and is an easy fix or
2. Is there a way to replicate the needed files to compile this that you know of?

Any help would be appreciated 😄

**Comment by mudlord** [comment]
Okay, I could upload the needed dependancies.

**Comment by DerekTurtleRoe** [comment]
Thanks for adding that, works now! 😄
